### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by EndaarF** [miniaturepets/citizens-integration#9]
# Bug Report

### Technical Information
* Paper 1.16.5 build 436
* 1.0
* Dump File: https://pastebin.com/uaHwMCyQ

### General Information
When an NPC pet exists, the error below is frequently logged. It's unclear what impact this has. You can teleport an NPC pet using /tphere, but it does not seem that they will follow you (head movement), nor does pathing work. Honestly the appearance bug is a bigger problem that led me to disable my NPC pets, so I didn't spend a lot of time troubleshooting this, but it seemed to occur consistently without any specific action.

**Instructions To Produce**
1. Create an NPC pet - the error should log shortly afterwards

[10:55:02] [Server thread/ERROR]: Could not pass event NPCTeleportEvent to Citizens v2.0.27-SNAPSHOT (build 2214)
java.lang.NullPointerException: null
        at net.miniaturepets.citizensintegration.MiniatureNpcTrait.onTeleport(MiniatureNpcTrait.java:54) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1303.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-436]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-436]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-436]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-436]
        at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:458) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.teleport(CitizensNPC.java:338) ~[?:?]
        at net.livecar.nuttyworks.npc_destinations.citizens.Citizens_Processing.lambda$locationReached$0(Citizens_Processing.java:378) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-436]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-436]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.5.jar:git-Paper-436]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-436]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-436]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-436]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-436]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

Thanks

**Comment by liorsl** [comment]
Hi,
It seems like you were using an outdated version, I believe this issue was already fixed.
